### ISSUE TITLE
Persistent notification | Again

### ISSUE THREAD

**Issue by Zeanon** [KieronQuinn/TapTap#185]
I tested it with different apps, like Gravity screen now
When I deactivate Gravity Screens persistent notification, it bugs out like Tap Tap, if the notification is enabled, it works perfectly fine.
I dont know how hard it would be to add a foregroundervicce with a persitent notification, but I'm pretty certain, it might fix the issue :)

**Comment by KieronQuinn** [comment]
Please stop suggesting this, accessibility services are not foreground services. They do not need to call startForeground with a notification, as they are a special case.

In fact, if you try to call startForegound and a notification, it does nothing, since the service has not been started with startForegroundService elsewhere in the app. 

Whatever Gravity Screen is doing, it's not the same as this app. I've checked the Accessibility Service code in that app, and it's not calling startForeground from within the accessibility service, so the notification is being used for another service and is not comparable to this app.
