### ISSUE TITLE
Feature request: Tap-Tap to capture picture

### ISSUE THREAD

**Issue by jhanitesh10** [KieronQuinn/TapTap#213]
Hi Team,
I am currently using this app in my Oneplus Nord device. Thanks a lot everyone for making such a great Application 👏 
While taking pictures, it really hard to reach out to the button on the screen or other short cut like clicking on the power button.
It would be great if we have the feature capture picture on `Tap-Tap`!

**Comment by KieronQuinn** [comment]
I tried to add this, but it's now impossible for an app to manually trigger the camera button, volume buttons or power button due to the restrictions on hidden APIs on recent Android versions. The accessibility controls bypass the buttons, so opening the power menu isn't the same as pressing power, and the volume controls are just calling the Media API rather than pretending a button has been pressed. 

There's no alternative that would work on all cameras that I can see, so I'm closing this unless anyone can suggest a way that would work.

**Comment by jhanitesh10** [comment]
Sure, Thanks @KieronQuinn for putting in the effort & letting me know.
