### ISSUE TITLE
[Feature Request] Gesture Test View and Debug Log Export for Back Tap activation issues

### ISSUE THREAD

**Issue by reinhart1010** [KieronQuinn/TapTap#241]
Hello,

I would like to recommend adding a Gesture Test View to the app to allow users to check whether their Tap, Tap configuration is correct and working for their device.

An ability to view and export debug log information would also be useful to solve and improve the Back Tap activation for certain devices (e.g. #31, #48, #83, #202, #225).

I'd also recommend encouraging issue reporters to report their device dimensions, as some of these devices does not perfectly fit with the Pixel 3/4 dimensions as used in the training model.

**Comment by KieronQuinn** [comment]
The next major feature I plan to work on is a setup wizard type UI, which will allow users to figure out the best size and sensitivity for their device before even starting the accessibility service, which should hopefully cover some of this. That method also doesn't rely on a background service for the initial experimenting, so it would rule out service killing issues, most of which the "not working" issues have turned out to be.

Debug log info would be useful, agreed. However, most of the logs are quite useless unless there's a crash, because the vast majority of the time, it either works or doesn't.

I also plan to add detection of display size (using DPI and resolution) to set a gesture model automatically, and probably will rename them to "Small", "Medium" and "Large" models, with the Pixel names as a side note.

**Comment by KieronQuinn** [comment]
Logging has been added in 1.0, for when the app crashes. There aren't any other logs in the app any more, so a general "log dump" from the app is not useful as it would not include system logs. In that case I would now recommend doing an actual system log report from the developer options.
