### ISSUE TITLE
Interferences with Google Chrome Omnibox

### ISSUE THREAD

**Issue by alejoma97** [KieronQuinn/TapTap#262]
When browsing on chrome, the search bar usually goes up and gets minimised as you scroll through the page so the experience is more immersive, I noticed that hadn't been the case for quite some time. 
After doing some research on the matter and trying some alternatives, I noticed that disabling TapTap services from the accessibility screen would indeed make the Omnibox get minimised again and work accordingly. 
(I only use TapTap for the multitask feature -dubbed _oppen recents_ on the app-, I have a feeling that might have something to do with the bug)

**Comment by AdityaAnand99** [comment]
Yes, I'm having the exact same problem in brave. The top address bar and the bottom toolbar don't auto-hide while scrolling, this is especially frustrating on a small phone.
![Screenshot_20200928-082112](https://user-images.githubusercontent.com/49330608/94385783-9d74ce00-0163-11eb-8788-da2c18e5e2ef.png)
 If I disable TapTap in accessibility settings then both the address bar and the bottom toolbar auto-hide when scrolling.

**Comment by KieronQuinn** [comment]
This isn't caused by Tap, Tap, directly, but was an intentional decision by the Chromium team for when an accessibility service with touch/gesture control is enabled: https://bugs.chromium.org/p/chromium/issues/detail?id=1028786

There isn't a workaround as it's an intentional thing and is out of my hands.
