### ISSUE TITLE
Add gates to tap types

### ISSUE THREAD

**Issue by Oi-Baba** [KieronQuinn/TapTap#275]
Is it possible to add gates to taps?
Like if I want tripple tap or double tap to work only if music is playing or when the screen is off?

**Comment by KieronQuinn** [comment]
Yes, adding a requirement of "music playing" or "display off" to all of your double/triple tap actions will do exactly that.

**Comment by Oi-Baba** [comment]
> 
> 
> Yes, adding a requirement of "music playing" or "display off" to all of your double/triple tap actions will do exactly that.

I know, but enabling tripple tap adds a delay right? I thought maybe adding gates to taps would help work around that

**Comment by KieronQuinn** [comment]
Gates on actions don't add much of a delay, the delay on double tap with triple tap enabled is significantly more than the delay you'd ever get with gates enabled. 

Adding gates also does not remove the delay on double tap with triple tap enabled, the delay is due to the laws of time (the app can't know if you're going to do a third tap before you do it)

**Comment by Oi-Baba** [comment]
>
> Adding gates also does not remove the delay on double tap with triple tap enabled, the delay is due to the laws of time (the app can't know if you're going to do a third tap before you do it)

Yes, what I meant was to have an option that'd only enable tripple tap when screen is off so that way double taps won't have the delay when the screen is on. Maybe gates wasn't the right term. But now that I think about it I don't think it'll be much usefull.
