### ISSUE TITLE
On OnePlus 8T every single tap emulates back button 

### ISSUE THREAD

**Issue by cisco187** [KieronQuinn/TapTap#297]
When active, any tap seems to simulate a swipe in from the left that creates a back swipe. None of the setting seem to fix it.

**Comment by KieronQuinn** [comment]
Any tap or any double tap? A single tap shouldn't be triggering it, ever.

**Comment by tommasoberlose** [comment]
@KieronQuinn I have the same problem on my 8T: I've set the double-tap to open the notifications panel but it seems to "lag". Most of the time the first trigger opens the panel and the second double-tap it closes it, but if there's a delay and I tap the back of the device 4/5 times then the go-back command is sent two times, even though the panel is closing or already closed.

Otherwise, often the first double-tap triggers the go-back command and then tries to open the notifications panel.
I didn't get if the commands are always alternate or if happened that the go-back command is sent more times in a row.
I don't know how the check of the notifications panel status is handled but it doesn't seem to be correct.

Would be possible to create two actions? One that just opens the notifications panel and one the toggles it?
Thank you!

**Comment by KieronQuinn** [comment]
What you're describing there is actually the compromise that was added because so many people pestered me to add open/close panel as a single option - it used  to be as you want (open only).

The reason it does it is that it's a hacky workaround - it doesn't know when the panel is closed, it just knows when the window next changes (eg. an app's screen changes, or you change app) - as then you've definitely closed the panel. There is no fix for this behaviour causing issues if you run the action, close the panel yourself and then run the action again without changing screen first.

**Comment by tommasoberlose** [comment]
Ook I get it, I've also made a quick search about it and it seems to be impossible to check the notifications panel status even using an overlay application.
Could be feasible to add the option to enable the "toggle" behavior inside the Requirements list though?

**Comment by 1LyRa** [comment]
I got same issue on Pixel 4XL.
I set my double tap to open notifications and that's all.
And sometimes when I want to open notifications, it doesn't open it and just do back button.

Is it possible to turn off close notification shade?
As I understand it causes issues and I don't need this feature anyway.

**Comment by KieronQuinn** [comment]
This should be improved in 1.0. If it's still happening, reply and I'll look at it again.
