### ISSUE TITLE
System lag

### ISSUE THREAD

**Issue by noahspooner** [KieronQuinn/TapTap#343]
Hello, I am using a Samsung Galaxy S10e and I've noticed that ever since installing this app, my system hasn't been as stable and I experience lag several times a day. It seems to usually happen when opening the notification shade but I've also seen it happen while swiping through pages on my home screen. I've run Geekbench test and my compute scores have gone down since installing this app. It is also interesting to note that it only seems to happen after my uptime is over 12h but never before. I will miss this app since I find double tapping on the back is a very intuitive way to screenshot but due to this issue and others such as accidental touches I will be uninstalling the app and waiting for the stable version of this app to come out to see if these are fixed.

**Comment by KieronQuinn** [comment]
I would guess that you're probably hitting this: https://www.xda-developers.com/working-as-intended-an-exploration-into-androids-accessibility-lag/, as the only thing that the accessibility service is doing when a window changes (which is what is happening when the notification shade opens) is updating a few fields. As this issue is in the system and is "working as intended", there's nothing I can do.

**Comment by noahspooner** [comment]
Ah ok then, I hope Google fixes this soon. Thank you.
