### ISSUE TITLE
Miui recommendation

### ISSUE THREAD

**Issue by jhernaez2004** [KieronQuinn/TapTap#361]
Hello I have your app tap tap in a Xiaomi Redmi phone and It doesn't work when you go outside de app.
I recommend you to request the permission to show above other applications It could make work better.

**Comment by drogga** [comment]
@jhernaez2004 are you completely sure that it's not just killed by the system optimizator(s) as soon as you leave it ?
...I don't think that "android.permission.SYSTEM_ALERT_WINDOW" will change anything...

**Comment by KieronQuinn** [comment]
> @jhernaez2004 are you completely sure that it's not just killed by the system optimizator(s) as soon as you leave it ?
> ...I don't think that "android.permission.SYSTEM_ALERT_WINDOW" will change anything...
> 
> @KieronQuinn the short app "About" description doesn't mention Pixel's, but only A11, which is misleading...
> Also in the change log of the latest build you claim that you removed the "Split Service" option (which is true), but you didn't seem to also removed the service itself from the "Accessibility Services" list, so at what point the app requires it to also be enabled, or is completely useless now ?
> 
> BTW - I must admit that, I'm not a big fan of the new notification that can't be completely and permanently hidden or removed from the shade, that takes place (even when put on "silent" from the notification settings, which btw are missing from the close to stock AOSP like 7.0 N firmwares \ ROMs)...

The permission might not be enough on its own, but drawing a 1x1 transparent overlay might be. Samsung's apps actually request the permission in order to stay running so there may be a point to this. 

As for the about screen, Android 11 DP1 was only on Pixels. We don't even know whether Columbus would've been a Pixel feature, or just an Android feature. 

The Accessibility Service *and* the foreground service (previously referred to as the "split service") are now required as that is the most robust way of keeping it running. I grew tired of people disabling the option (after it was made default) or not enabling it (before) and complaining it was killed, so they were merged into one. The accessibility service is an absolute requirement as (almost) all the actions and some gates rely on it in some way.

The notification CAN be hidden, just turn it off in the system settings. Don't change it to silent, literally just turn the switch off. As that's blocking it on the system level, it has no effect on it being killed, so is safe to do. Foreground services require notifications, so it is a must as a side effect of the above service changes.

**Comment by drogga** [comment]
I wasn't talking about any screen, but the short description of the app here in GitHub...
Many, many devices from different brands\manufacturers nowadays even come straight with A11, so I'm not following I'm afraid - regarding the rest of your explanation about this...

I was obviously talking about the 2nd additional (and optional) service that the app didn't required it at any point on 2 of my friends devices - Poco x3 NFC & SGS21, but it's still there (it persists to be available).

OK, it will be disabled\turned off then, I just hope that you are right in claiming that it won't make the app more "kill-able" by the system, especially on Huawei, Xiaomi and other brand's devices with android forks & custom skins (frameworks) with heavy app killers \ optimizators ;)

**Comment by KieronQuinn** [comment]
> I wasn't talking about any screen, but the short description of the app here in GitHub...
> Many, many devices from different brands\manufacturers nowadays even come straight with A11, so I'm not following I'm afraid - regarding the rest of your explanation about this...
> 
> I was obviously talking about the 2nd additional (and optional) service that the app didn't required it at any point on 2 of my friends devices - Poco x3 NFC & SGS21, but it's still there (it persists to be available).
> 
> OK, it will be disabled\turned off then, I just hope that you are right in claiming that it won't make the app more "kill-able" by the system, especially on Huawei, Xiaomi and other brand's devices with android forks & custom skins (frameworks) with heavy app killers \ optimizators ;)

Ah I understand now. That could be better, I'll update it when the app goes to stable soon along with the screenshots. 

The secondary gesture service the app requires when you use the hamburger or swipe actions. It's a separate service for the reason it states in its description - services that can interact with the screen with gestures (hamburger is also a gesture internally) cause some problems for apps like Chrome, so making the main service handle this as it was originally caused disruption for users, hence it becoming a second service. You don't need to enable it if you don't use those four actions (in fact the app will prompt you to *disable* it if you have it on without using them), it makes no difference to how the app works otherwise. 

As for the crash, I'm pushing a bug fix release out that fixes it tomorrow.

**Comment by drogga** [comment]
@KieronQuinn ^ when you read it, but let's say that you don't want to reply for some reason, please put a reaction emoji, so I can at least know that it's been read by you - thanks.

**Comment by drogga** [comment]
Please forgive my ignorance..., I thought that the so called and now since recently removed "split service" option was to use the second optional service, and not to split in half the main one in the backend (under the hood).

I was hoping for a Debug build also for another reason - to try somehow to get a traceback \ logcat or whatever crash log of this app only on HTC device with 7.0 Nougat on which I can't get those otherwise, because the microUSB port is busted and can only be used for charging (data lines are the issue it seems, not the cable), plus I no longer have a PC - even if it worked, in order to use ADB to get the crash log (since in the "Debug" builds should have injected \ build-in debugger\bug tracker - as far as I know...)

...I'm out of options...

**Comment by drogga** [comment]
Please forgive my ignorance..., I thought that the so called and now since recently removed "split service" option was to use the second optional service, and not to split in half the main one in the backend (under the hood).

I was hoping for a Debug build also for another reason - to try somehow to get a traceback \ logcat or whatever crash log of this app only on HTC device with 7.0 Nougat on which I can't get those otherwise, because the microUSB port is busted and can only be used for charging (data lines are the issue it seems, not the cable), plus I no longer have a PC - even if it worked, in order to use ADB to get the crash log (since in the "Debug" builds should have injected \ build-in debugger\bug tracker - as far as I know...)

...I'm out of options...

Can't you integrate crash report-er of some sort, like the one in NewPipe or the AIDA solution, which either shows you a visible log if it crashes, or saves it as a text file file somewhere on a accessible place on the internal storage and you can copy-paste the log here in a issue ?

**Comment by KieronQuinn** [comment]
> @KieronQuinn - Please forgive my ignorance..., I thought that the so called and now since recently removed "split service" option was to use the second optional service, and not to split in half the main one in the backend (under the hood).
> 
> I was hoping for a Debug build also for another reason - to try somehow to get a traceback \ logcat or whatever crash log of this app only on HTC device with 7.0 Nougat on which I can't get those otherwise, because the microUSB port is busted and can only be used for charging (data lines are the issue it seems, not the cable), plus I no longer have a PC - even if it worked, in order to use ADB to get the crash log (since in the "Debug" builds should have injected \ build-in debugger\bug tracker - as far as I know...)
> 
> ...I'm out of options...
> 
> Can't you integrate crash report-er of some sort, like the one in NewPipe or the AIDA's solution, which either shows you a visible log if it crashes, or saves it as a text file somewhere on a accessible place on the internal storage and you can copy-paste the log here in a issue ? It will be super useful and convenient to everyone that has "critical" FC issues with the app.

A crash logging system may be added eventually (there's a ticket for it #241) but it's not a top priority at the moment. Simply using a debug build does not do anything for bug tracking, there's no built in log reporting on Android that gets enabled for debug builds.

**Comment by drogga** [comment]
But it should be a priority...!
I thought that "leak canary" [https://square.github.io/leakcanary/] can be used (tho I don't know exactly what I'm talking about...).
Developer Options > "Select debug app" {select app to be debugged} - I don't understand then for what and how is this being used by some, because if a app doesn't contain a debug code (isn't a debug build), it simply doesn't show up in the list of this sub-menu in order to be selected...

I'm waiting for the promised fix today...

**Comment by Bradford1040** [comment]
Wow, "promised fix"

I am not trying to speak out of turn or for anyone, or trying to sound like a jerk.

This is a wonderful "FREE" app, you remember that right?

Or am I wrong and owe an apology?

**Comment by KieronQuinn** [comment]
> But it should be a priority...!
> I thought that "leak canary" [ https://square.github.io/leakcanary/ ] can be used (tho I don't know exactly what I'm talking about...).
> Developer Options > "Select debug app" {select app to be debugged} - I don't understand then for what and how is this being used by some, because if a app doesn't contain a debug code (isn't a debug build), it simply doesn't show up in the list of this sub-menu in order to be selected...
> 
> I'm waiting for the promised fix today...

Why should it be a priority when it's only a small subset of users who a) need the feature and b) can't use adb or are rooted/can use Shizuku to capture a log on the device? Leak Canary requires a gradle dependency which while I may use internally, I certainly wouldn't release a build with enabled. If you want to add it for your own use, fork it and add it yourself, it's not my job to add tiny additions that serve one or two users out of everyone.

**Comment by drogga** [comment]
NVM, the app doesn't detect the sensor(s) of my HTC M9 - no matter what, and that's it, even tho the G-sensor is calibrated, that on the initial setup wizard, which crashes only sometimes now, so there's basically no point in any logs regarding the detection, maybe only for the occasional crash in setup, but given that it's useless for me, there's no point in dealing with it anymore...

BTW - The virtual (software) NavBar is still invisible (with 100% of transparency) and I can't see where the buttons are exactly, fix it if you want, your choice, it doesn't matter for me anymore - I gave up.

Best regards, take care ;)

**Comment by drogga** [comment]
@Bradford1040 - My ENg isn't native, so please forgive me for my expressions, I only have the best intentions and I didn't meant to offend anyone.

**Comment by Bradford1040** [comment]
> @Bradford1040 - My ENg isn't native, so please forgive me for my expressions (or poor choice of words), I only have the best intentions and I didn't meant to offend anyone.

@drogga - I totally get it, and my apologies to you. The way your post came out basically fit other users that yell at dev's like they owe them something on a free app, that the dev has graciously shared via open source. I see that this wasn't your intention. You have a great day as well

**Comment by KieronQuinn** [comment]
The 1.0 rewrite changed how services work so this should no longer be an issue.
