### ISSUE TITLE
Not Working well on Mi 9T

### ISSUE THREAD

**Issue by b-bertonzin** [KieronQuinn/TapTap#39]
I have an issue with the app on my Mi 9T running MIUI 12. It works only one time, then I have to restart my device. Then it works more one time and that is it.

Awesome app, by the way. Great idea!!!

EDIT: I realized that the app stops working when I leave it or close it. Then I need to restart so it can work again. But the app stops again in the first time I leave the app again.

**Comment by KieronQuinn** [comment]
This is caused by OEMs breaking the fundamental requirement of accessibility services needing to always be running in the background. Try disabling battery optimisation for Tap, Tap, and if that doesn't work there's nothing I can do about it. MIUI is one of the worst for messing with the system to the point of it being broken.
