### ISSUE TITLE
Getting app shortcuts results in crash

### ISSUE THREAD

**Issue by MKCOOL142** [KieronQuinn/TapTap#455]
[tap_tap_crash_report_2022-01-23T20_13_18.424.txt](https://github.com/KieronQuinn/TapTap/files/7921210/tap_tap_crash_report_2022-01-23T20_13_18.424.txt)
That's my crash log

**Comment by KieronQuinn** [comment]
This is an App Shortcuts issue, not Shizuku. What ROM are you using? I assume you're using one as the fingerprint says Coral but the device is a 7 Pro

**Comment by MKCOOL142** [comment]
Yes I have a OnePlus 7 Pro but spoofed the fingerprint

**Comment by KieronQuinn** [comment]
So just stock ROM? Are you using Shizuku (started as root? or adb?) or Sui?

**Comment by MKCOOL142** [comment]
Yes Stock Rom, I'm using Shizuku in root mode and already granted the permission

**Comment by KieronQuinn** [comment]
Strange, using identical config on my 7T Pro it works fine. Could you try installing Sui (it's on the Magisk repo) and using that? It's basically Shizuku but made for root, and might handle this better - it seems the root-started Shizuku service is failing to switch to `shell` - this issue: https://github.com/RikkaApps/Shizuku-API/issues/8

Alternatively, stop Shizuku (in the menu of the Shizuku app) and start it using ADB rather than root. 

The fix is already implemented in Tap, Tap so if it doesn't work on some devices I'll have to add a special error for when it happens, telling people to either use Sui or start Shizuku with ADB.

**Comment by MKCOOL142** [comment]
[tap_tap_crash_report_2022-01-23T21_26_15.991.txt](https://github.com/KieronQuinn/TapTap/files/7921346/tap_tap_crash_report_2022-01-23T21_26_15.991.txt)
Tried to use adb, got this

**Comment by KieronQuinn** [comment]
Ok it's working then, just one of the shortcuts is mangling the filename for the cache, I'll look into it thanks

**Comment by MKCOOL142** [comment]
I also uninstalled shizuku, installed sui and got this error crash now 
[tap_tap_crash_report_2022-01-23T21_42_30.964.txt](https://github.com/KieronQuinn/TapTap/files/7921369/tap_tap_crash_report_2022-01-23T21_42_30.964.txt)

**Comment by KieronQuinn** [comment]
This is now **handled** in 1.0.1. There is no fix, as it's the system server rejecting the call. The workaround is to use Shizuku.

I'm not sure if the mangled filenames will be handled better by this or not - if you still get a crash using ADB post a log again :)

**Comment by MKCOOL142** [comment]
[tap_tap_crash_report_2022-01-24T19_31_41.882.txt](https://github.com/KieronQuinn/TapTap/files/7927982/tap_tap_crash_report_2022-01-24T19_31_41.882.txt)
Sadly it's still crashing :/ (I might've dome something wrong but this was with Shizuku using the wireless adb)

**Comment by MKCOOL142** [comment]
This is still happening in Version 1.1 ![tap_tap_crash_report_2022-02-12T11_50_36.592.txt](https://github.com/KieronQuinn/TapTap/files/8053213/tap_tap_crash_report_2022-02-12T11_50_36.592.txt)
