### ISSUE TITLE
Become not supported after updating Tap, Tap

### ISSUE THREAD

**Issue by heqyoufree** [KieronQuinn/TapTap#483]
In brief
0.9 beta works fine but when I tried to update to newer (all newer version are checked) , Tap, Tap refuses to run and reminds me that my device do not have a gyroscope. When I check DevCheck, my device do have a gyroscope. 

Expected
Tap, Tap works as previous version

Actual
Tap, Tap refuses to run

Details
Device: LG V50 ThinQ (LGE-V500N Varient)
Android version: Android 12 (SQ1A.220105.002)
Tap, Tap version: 0.10 beta～1.0.1

**Comment by KieronQuinn** [comment]
The gyroscope check comes from the system, your device is reporting it does not have a gyroscope. Perhaps the other check you are doing is using a non-standard method, which is something I won't be doing to fix issues caused by OEMs. 

https://github.com/KieronQuinn/TapTap/blob/5a648d795c1f12cdd4930d548eb745f5a5f21713/app/src/main/java/com/kieronquinn/app/taptap/utils/extensions/Extensions%2BContext.kt#L161

**Comment by heqyoufree** [comment]
Thanks for your reply, but i still hope that you can add a button like "continue anyway" because there is nothing I can do to the system.

**Comment by anht3889** [comment]
@heqyoufree You can reuse deviceHasGyroscope() from ver 0.9 to bypass the gyroscope sensor checking.
