### ISSUE TITLE
Still asking for external access even with it enabled in tasker 

### ISSUE THREAD

**Issue by Schism169** [KieronQuinn/TapTap#509]
![Screenshot_20220410-144559_Tasker](https://user-images.githubusercontent.com/20604331/162641368-eba36222-2485-4836-9da4-66a97db15682.jpg)
Taptap keeps asking for tasker to enable external access even though it has already been given.

**Comment by KieronQuinn** [comment]
The permission requirement comes directly from the Tasker SDK, any issue will be on its side. Usually this is caused by Tasker changes not being commited - close out the settings and make sure there's no check button in the toolbar. If there is, tap it to save the settings. Otherwise, reboot.

There's nothing else that can be done on Tap, Tap's side.
