### ISSUE TITLE
Notification shade needs manual opening after unlock

### ISSUE THREAD

**Issue by lilithium-hydride** [KieronQuinn/TapTap#516]
After locking and unlocking the device, the notification shade action doesn't do anything until it's been manually opened. The vibration triggers, so the service has definitely not been killed. For what it's worth, this exact issue also occurred with the system's own fingerprint scanner gesture on my Pixel 3 (stock and non-stock OS). Current device is a Pixel 6 running GrapheneOS. I didn't see anywhere to grab a log, apologies if I missed something there.

**Comment by KieronQuinn** [comment]
This is because Android doesn't give me a way to know if it's opened, the action is entirely dependent on knowledge of whether it was previously opened. If it gets out of sync, you have to trigger it manually for it to open and get back in sync. Until Android provides a way to know whether it's open (and I highly doubt it ever will), I can't do anything about this.

**Comment by lilithium-hydride** [comment]
Makes sense, thanks!
