### ISSUE TITLE
Can't use additional tasks after the launch app task

### ISSUE THREAD

**Issue by ajpalasky1** [KieronQuinn/TapTap#546]
I have it set up for double tap to launch Snapchat, and a task underneath to go to the last used app after another double tap with a restriction to only run while in Snapchat. When I double tap it opens snap, when I do it again it goes to the last app. But when I double tap to open snap and use it for a little bit and try the double tap to go back, it vibrates like it registered but doesn't do anything. All permissions have been enabled including all accessibility

**Comment by KieronQuinn** [comment]
That sounds like the system is telling Tap, Tap that a different app has launched and it's re-running the QTTS task. Unfortunately since that's the only way to monitor foreground apps universally with any reliability, there's nothing I can do. The implementation to fix this (skipping tasks while the app is already launched) is already there.
