### ISSUE TITLE
Help testing on Android 14

### ISSUE THREAD

**Issue by k2helix** [KieronQuinn/TapTap#592]
Hi, I installed Tap Tap so that I can toggle the flashlight by double tapping the back of the phone even when the screen is off. I'm currently running latest GrapheneOS (Android 14) on a Pixel 8.

However, whereas the app is not being killed in the background (it appears under quick settings as a running app and battery optimisations are disabled), when the screen is off the gesture only works for some seconds then stops responding. After turning the screen on, it starts working again but when turning the screen off this happens every time. Note that this happens with every action, not just the toggle flashlight one.

I asked in the xda forum of the app if it could be anything related to the sensors the app uses (gyroscope and accelerometer) that stop responding when the screen is not awake, and was answered that it might be the cause. I then asked my ROM developers and they answered that this wouldn't be related to GrapheneOS and that it should be tested on regular Android 14.

I currently can't spend that much time reflashing stock ROM and configuring everything again, so I would appreciate any kind of help at testing or knowing what is the root of this issue. I don't know if I should label this as service killed or help wanted. Thanks in advance.

**Comment by KieronQuinn** [comment]
The app has worked fine on Android 14 since the first developer preview. Given 14's rollout now on many devices, I find it very unlikely that it would be a global issue and is far more likely to be an issue with your ROM. 

All I can suggest is checking for ROM-specific battery optimisations and disabling them, but it sounds like you've already done that so there's nothing else I can really suggest.

**Comment by witooski** [comment]
@k2helix, although it's been nearly 1,5 years since you reported this issue with Tap Tap being killed on GrapheneOS running on your Pixel8, I believe I've found a solution. You need to enable 'Tap Tap' in the Accessibility menu under GrapheneOS settings (Settings > Accessibility > Tap Tap).

After enabling this option, Tap Tap no longer gets killed when the screen turns off. I've been testing this for the last 15 minutes, and it works perfectly.

**Comment by k2helix** [comment]
@witooski Thanks for your reply! Sadly, I already tried this and it didn't work. I just tried it in case something changed but nothing. I don't feel *the app* is getting killed but *the sensor* stops working for some reason. But that's just intuition.

**Comment by witooski** [comment]
That's weird... I'm running the latest release of GrapheneOS (Android 15) on my Pixel 8. I have the latest version of available version of Tap Tap (1.6.2) with double tap to toggle torch working perfectly fine with screen of.

You may want to chceck the following:
- Tap Tap should be enabled under Accessibility menu in GrapheneOS Settings (Settings > Accessibility > Tap Tap). 
- Battery Optimization is turned off for Tap Tap (Settings > Applications > Tap Tap > Battery...) 
- No Gates are defined within Tap Tap. Please note that by default there is a gate defined for "screen off" that prevents double tap to work with screen off. Apparently there is some bug in the app that even if you delete this gate from app and then dismiss the information hint/box in gates, the previously defined gates (there are two) come back... (Open Tap Tap > Gates > Remove all defined Gates).

**Comment by k2helix** [comment]
I checked all 3 things and nothing, the same weird behaviour where it works for some seconds after turning the screen off and then nothing. Thanks for your help though!

**Comment by k2helix** [comment]
Well not exactly the same behaviour. When the screen is off, it works fine for some seconds (if I don't stop double tapping it works but as soon as I stop for 2 seconds it doesn't)  then I have to tap tap multiple times in order for the flashlight to turn on. But sometimes it won't work. Not sure if this happened when I first created the issue.
