### ISSUE TITLE
Not working on Android 15 (GrapheneOS / Pixel 8 Pro)

### ISSUE THREAD

**Issue by nodeam** [KieronQuinn/TapTap#614]
@KieronQuinn

Blocked in Accessibility API, probably due to this: https://www.androidauthority.com/android-15-restricted-settings-sideloading-3481098/
All my F-Droid Apps get access to Accessibility API, thus please consider an upload to F-Droid.

**Comment by KieronQuinn** [comment]
Nothing to do with Android 15, the accessibility "block" on sideloading has existed since Android 13. You can just bypass them: https://support.google.com/android/answer/12623953?hl=en-GB#:~:text=safe%20online.-,Allow%20restricted%20settings,-Important%3A

F-Droid doesn't allow in-app updates or the Play Services dependencies, this has been discussed previously in #521.
