### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Vikkynps** [KieronQuinn/TapTap#62]
Back gesture not working on my poco f1

**Comment by KieronQuinn** [comment]
#48

**Comment by Jefferderp** [comment]
This isn't a duplicate of #48.

I'm experiencing the same on my _Xiaomi Mi 9T Pro_ (aka _Redmi K20 Pro_). **Everything** works great, except for specifically the 'back' button gesture. Home, Recents, Flashlight, etc. all work great. It's just the 'Back button' gesture that doesn't respond.

I'm using an AOSP rom (not the factory MIMU skin) so I don't know why this would be. I'm also using Android Q's '2-button navigation' feature, if it's relevant - but this still offers a dedicated back button.

Thanks!

**Comment by KieronQuinn** [comment]
It's highly likely to be a duplicate of 48, you're only not experiencing the issue because you're using an AOSP ROM, 48 is caused by MIUI, which the F1 runs. 

As for your back button issue, the service runs the built in accessibility back button function, so there's nothing I can really do about that. An alternative might be possible with root, if lots of people find it doesn't work for them either, but there's been hardly any reports of it happening yet.

**Comment by Jefferderp** [comment]
OK, you got it! Thanks for the help :)
