### ISSUE TITLE
How will gates for specific actions work?

### ISSUE THREAD

**Issue by Oi-Baba** [KieronQuinn/TapTap#74]
So I was just wondering how this will be executed and this is what I have in mind:

Tapping the action will bring up a menu to add gates to it
Then there would be global gates like now
So it'll go something like  Trigger -> Action -> Action's Gates -> Global Gates (-> go to next action if action fails)

Just asking

**Comment by KieronQuinn** [comment]
It'll go like this

onTrigger:
if isBlockedByGlobalGate -> return (cancel)
for each action:
   if isBlockedByActionsGates -> skip
   else run action -> return (cancel)

So basically it'll check the global gates first and block all actions if any of those are blocking, and otherwise will walk through the actions as usual, skipping them if any of the gates attached to it are blocked

The idea will be that you set gates like screen off or in pocket (when I manage to add that) as global gates, and gates like "App not running" (just an inverse of the current app running one) to the actions to make them run on a per-app basis. Either that or I add something that inverts the behaviour of the action gates but not the global gates.

Hope that explains it well enough.

**Comment by Oi-Baba** [comment]
Yup, thanks
