### ISSUE TITLE
Battery drainage

### ISSUE THREAD

**Issue by roizcorp** [KieronQuinn/TapTap#86]
Samsung Galaxy S9, Lineage OS 17.1

no gates configured, app takes 10% CPU

I disabled the gates of both screen on and off in order to utilize it in different scenarios

I suppose that as a mitigation you could allow Tasker "to turn the app" on and off in certain situations that Tasker will define, this way the app will work in a certain use cases, - in other words is to allow Tasker become a gate or a tasker action to set it on and off

Keep up the great work!

**Comment by bhaskar452** [comment]
I am also facing this problam

**Comment by Oi-Baba** [comment]
Well the app has to monitor various sensors to work properly so I guess that is to be expected

> I disabled the gates of both screen on and off in order to utilize it in different scenarios

can you please tell what they are

**Comment by roizcorp** [comment]
I'm sorry, can you elaborate your question?

Don't get me wrong,  I love it! but in terms of drainage 10% for sensor is a little too high I suppose it is you have some sort of time interval to check the sensors rather than event based?

Also I suggest that indeed tasker could turn it on and off given certain condition that could help managing the power consumption
What do you think?

**Comment by shivangchopra22** [comment]
v0.3 is better than v0.4 in terms of battery. And I found a somewhat fix for the battery drain: using naptime and enabling battery optimization for tap tap. On v4 and battery optimization disabled, my battery drained a lot when I was sleeping (meaning doze wasn't enabled probably) and not only the battery drain increased(when using the phone normally) but time taken to charge the phone also increased (compared from 20% to 80%). Since I've come back to v3 and re-enabled battery optimization, my battery drain (both when screen is on and off) have decreased comparitively and the time taken to charge the phone has also decreased. 
I'm on redmi note 7 pro

**Comment by KieronQuinn** [comment]
Post rewrite, this is now as efficient as it can be. Possible the changes in Android 12 may help this (especially if it makes it to the release this time), but all I can do has now been done. The ability to turn the service off entirely from Tasker still needs to be looked at, however.

**Comment by KieronQuinn** [comment]
Low Power Mode was indeed added in Android 12, and 1.0 can work with them. Tasker support has been added, see #421
